[tool.poetry]
name = "jobo-scraper"
version = "1.0.2"
description = "Jobo web scraper for get the current available events."
authors = ["Luis Gómez Alonso <luis.gomez.alonso95@gmail.com>"]
readme = "README.md"
license = "Apache 2.0"
homepage = "https://github.com/Luis-GA/jobo-scrapper"
repository = "https://github.com/Luis-GA/jobo-scrapper"
keywords = [
    "jobo", "madrid", "cultura"
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
